### ISSUE TITLE
Got The Warning For ARC Retain Cycle

### ISSUE THREAD

**Issue by afiq90** [owlcoding/SimpleAudioPlayer#4]
![simpleaudioplayer](https://cloud.githubusercontent.com/assets/8640517/5602730/e5c98bc2-939c-11e4-9531-c8a180e3f8d4.png)

How can i fix this warning?

**Comment by drinking** [comment]
I have the same question and posted this to stackoverflow at 
http://stackoverflow.com/questions/27959720/how-to-avoid-retain-cycle-warning-when-a-block-try-to-set-its-self-to-nil

**Comment by afiq90** [comment]
thank you for posting this question to stackoverflow.
